import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { Header } from "../components/Header";
import { Content } from "../components/Content";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content>
        <Header title={`ヘッダー`} />
        <main>
          <h1>about</h1>
          <p>
            <Link href={`/`}>トップへ</Link>
            <Link href={`/`}>
              <button>トップへ2</button>
            </Link>
          </p>
        </main>
      </Content>
    </>
  );
}
