import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import useSWR from "swr";
import Header from "./components/Header";
import Content from "./components/Content";
import { DataType } from "./api/message";

export default function Home() {
  async function fetcher(url: string): Promise<DataType> {
    const response = await fetch(url);
    return response.json();
  }
  const { data, error } = useSWR("/api/message", fetcher);
  if (error) return <div>failed to load</div>;
  if (!data) return <div>loading...</div>;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content>
        <Header title={`ヘッダー`} />
        <main>
          <h1>ああああ</h1>
          <Link href={`/about`}>aboutへ</Link>
          <p>{data.name}</p>
        </main>
      </Content>
    </>
  );
}
