import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Content } from "./components/Content";
import Link from "next/link";
import { Header } from "./components/Header";
import useSWR from "swr";
import { fetcher } from "./fetch/fetcher";

export default function Home() {
  const { data, error } = useSWR("/api/hello", fetcher);
  if (error) return <div>failed to load</div>;
  console.log(data);
  if (!data) return <div>loading...</div>;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content>
        <Header title={`ヘッダー`} />
        <main>
          <h1>ああああ</h1>
          <Link href={`/about`}>aboutへ</Link>
          <p>{data.name}</p>
        </main>
      </Content>
    </>
  );
}
